version: '3.6'
services:
###################################################################################################
  nodered:
    image: nodered/node-red
    container_name: nodered
    restart: always
    volumes:
      - ~/docker/nodered:/data
    network_mode: host
    ports:
      - 60000:60000
      - 1880:1880
      - 80:80
    privileged: true
    user: root:root
    environment:
      - TZ=Europe/Berlin
###################################################################################################
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: always
    network_mode: host
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ~/docker/mosquitto:/mosquitto/
###################################################################################################
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    container_name: zigbee2mqtt
    restart: always
    network_mode: host
    volumes:
      - ~/docker/zigbee2mqtt/data:/app/data
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
###################################################################################################
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - ~/docker/influxdb:/var/lib/influxdb
    restart: always
    environment:
     - INFLUXDB_DB=db0
     - INFLUXDB_ADMIN_USER="admin"
     - INFLUXDB_ADMIN_PASSWORD="password"
###################################################################################################
  grafana:
    image: grafana/grafana
    container_name: grafana
    network_mode: host
    ports:
      - 3000:3000
    volumes:
      - ~/docker/grafana:/var/lib/grafana
    restart: always
    user: root:root
